-- MySQL Script generated by MySQL Workbench
-- Tue Apr 26 08:42:25 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema software_storage
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `software_storage` ;

-- -----------------------------------------------------
-- Schema software_storage
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `software_storage` DEFAULT CHARACTER SET utf8 ;
USE `software_storage` ;

-- -----------------------------------------------------
-- Table `software_storage`.`product_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `software_storage`.`product_info` ;

CREATE TABLE IF NOT EXISTS `software_storage`.`product_info` (
  `_id` INT NOT NULL AUTO_INCREMENT,
  `product_name` VARCHAR(45) NOT NULL,
  `creator_id` VARCHAR(20) NOT NULL,
  `creator_email` VARCHAR(45) NOT NULL,
  `creator_pic_url` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`_id`),
  INDEX `idx_name` (`product_name` ASC) VISIBLE,
  FULLTEXT INDEX `full_idx_name` (`product_name`) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `software_storage`.`file_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `software_storage`.`file_info` ;

CREATE TABLE IF NOT EXISTS `software_storage`.`file_info` (
  `_id` INT NOT NULL AUTO_INCREMENT,
  `product_id` INT NOT NULL,
  `file_name` VARCHAR(45) NOT NULL,
  `latest_change_time` TIMESTAMP NOT NULL,
  PRIMARY KEY (`_id`),
  INDEX `fk_file_info_product_info1_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_file_info_product_info1`
    FOREIGN KEY (`product_id`)
    REFERENCES `software_storage`.`product_info` (`_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `software_storage`.`file_content`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `software_storage`.`file_content` ;

CREATE TABLE IF NOT EXISTS `software_storage`.`file_content` (
  `_id` INT NOT NULL AUTO_INCREMENT,
  `file_info_id` INT NOT NULL,
  `file_url` VARCHAR(200) NOT NULL,
  `file_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`_id`),
  INDEX `fk_idx_f_id` (`file_info_id` ASC) VISIBLE,
  CONSTRAINT `fk_to_show_content`
    FOREIGN KEY (`file_info_id`)
    REFERENCES `software_storage`.`file_info` (`_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `software_storage`.`file_edition`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `software_storage`.`file_edition` ;

CREATE TABLE IF NOT EXISTS `software_storage`.`file_edition` (
  `_id` INT NOT NULL AUTO_INCREMENT,
  `file_info_id` INT NOT NULL,
  `file_id` INT NOT NULL,
  `next_id` INT NULL DEFAULT '0',
  PRIMARY KEY (`_id`),
  INDEX `fk_idx_content_id` (`file_id` ASC) VISIBLE,
  INDEX `idx_file_info_id` (`file_info_id` ASC) VISIBLE,
  CONSTRAINT `fk_to_control_edition`
    FOREIGN KEY (`file_id`)
    REFERENCES `software_storage`.`file_content` (`_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `software_storage`.`user_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `software_storage`.`user_info` ;

CREATE TABLE IF NOT EXISTS `software_storage`.`user_info` (
  `_id` INT NOT NULL AUTO_INCREMENT,
  `user_log_id` VARCHAR(20) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `create_time` TIMESTAMP NOT NULL,
  `latest_logon` TIMESTAMP NULL DEFAULT NULL,
  `profile_pic_url` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_log_id` ASC) VISIBLE,
  INDEX `idx_u_id` (`user_log_id` ASC) INVISIBLE,
  INDEX `idx_passwd` (`password` ASC) INVISIBLE,
  INDEX `idx_email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `software_storage`.`participation_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `software_storage`.`participation_info` ;

CREATE TABLE IF NOT EXISTS `software_storage`.`participation_info` (
  `_id` INT NOT NULL AUTO_INCREMENT,
  `u_id` INT NOT NULL,
  `p_id` INT NOT NULL,
  PRIMARY KEY (`_id`, `u_id`, `p_id`),
  INDEX `fk_idx_u_pa` (`u_id` ASC) VISIBLE,
  INDEX `fk_idx_p_pa` (`p_id` ASC) VISIBLE,
  CONSTRAINT `fk_to_be_particepated`
    FOREIGN KEY (`p_id`)
    REFERENCES `software_storage`.`product_info` (`_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_to_particepate`
    FOREIGN KEY (`u_id`)
    REFERENCES `software_storage`.`user_info` (`_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `software_storage`.`star_of_product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `software_storage`.`star_of_product` ;

CREATE TABLE IF NOT EXISTS `software_storage`.`star_of_product` (
  `_id` INT NOT NULL AUTO_INCREMENT,
  `u_id` INT NOT NULL,
  `p_id` INT NOT NULL,
  `stared_time` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`_id`, `u_id`, `p_id`),
  INDEX `fk_idx_u_s` (`u_id` ASC) VISIBLE,
  INDEX `fk_idx_p_s` (`p_id` ASC) VISIBLE,
  INDEX `idx_s_time` (`stared_time` ASC) VISIBLE,
  CONSTRAINT `fk_to_be_stared`
    FOREIGN KEY (`p_id`)
    REFERENCES `software_storage`.`product_info` (`_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_to_star`
    FOREIGN KEY (`u_id`)
    REFERENCES `software_storage`.`user_info` (`_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `software_storage`.`watch_of_product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `software_storage`.`watch_of_product` ;

CREATE TABLE IF NOT EXISTS `software_storage`.`watch_of_product` (
  `_id` INT NOT NULL AUTO_INCREMENT,
  `u_id` INT NOT NULL,
  `p_id` INT NOT NULL,
  `latest_watched_time` TIMESTAMP NOT NULL,
  PRIMARY KEY (`_id`, `u_id`, `p_id`),
  INDEX `fk_u_w` (`u_id` ASC) VISIBLE,
  INDEX `fk_p_w` (`p_id` ASC) VISIBLE,
  INDEX `idx_w_time` (`latest_watched_time` ASC) VISIBLE,
  CONSTRAINT `fk_to_be_watched`
    FOREIGN KEY (`p_id`)
    REFERENCES `software_storage`.`product_info` (`_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_to_watch`
    FOREIGN KEY (`u_id`)
    REFERENCES `software_storage`.`user_info` (`_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
